### ISSUE TITLE
Relax structure data available?

### ISSUE THREAD

**Issue by hongshuh** [HSE-LAMBDA/ai4material_design#38]
Hi, it's a very interesting research focus on defects, I wonder if the relax structure files available?

**Comment by kazeevn** [comment]
Hello!

Thank you for your interest! Yes, the relaxed structures are available, along with the full VASP output. To obtain:
1. Clone the repository
2. Ensure that [DVC[S3]](https://dvc.org/doc/user-guide/data-management/remote-storage/amazon-s3) is installed, for example by running `pip install dvc[s3]`
3. Download the VASP output: `dvc pull -R datasets/raw_vasp/high_density_defects datasets/raw_vasp/dichalcogenides8x8_vasp_nus_202110`
4. The relaxed structures are contained in the [CONTCAR](https://www.vasp.at/wiki/index.php/CONTCAR) files
5. Some of the data are packed into `tar.gz`, as its unpacked size is ~300Gb. You might want to use [ratarmount](https://github.com/mxmlnkn/ratarmount) to work with it.

**Comment by kazeevn** [comment]
Properly [documented](https://github.com/HSE-LAMBDA/ai4material_design/blob/main/docs/DATA.md#raw-vasp-output) the data acquisition procedure. Thank you for raising the matter! Feel free to ask if you have any further questions.
