### ISSUE TITLE
Combined Dataset 

### ISSUE THREAD

**Issue by hongshuh** [HSE-LAMBDA/ai4material_design#39]
Hi, thanks for your providing dataset. 
I downloaded the combined dataset from [Constructor Research Platform](https://research.constructor.tech/open/2d-materials-point-defects). I found NaN value in formation energy, band_gap and total_mag. And the formation energy is all -7.0 as well as there is only 0.0,1.0,2.0 in band gap. I also check other dataset and there are no such error, I guess you might have some mistake when combining all datasets. Could you update it or am I downloaded a wrong file?

**Comment by kazeevn** [comment]
Hello again! Thank you for the report! I'll investigate.

**Comment by kazeevn** [comment]
Hi!

There is indeed a problem with the combined dataset. We'll fix it. In short term, can you try the [archive](https://research.constructor.tech/open/2d-materials-point-defects/attachments/5189da66f7c0417d91a996cdcb83c155?name=2d-materials-point-defects-all.zip)?

`targets.csv.gz` contains the energy, band gap and magnetization, along with a variety derived variables:

- `energy` is the potential energy as reported by VASP
- `formation_energy` is the defect formation energy, computed according [equation 1 from the paper](https://www.nature.com/articles/s41524-023-01062-z#Sec5)
- `formation_energy_per_site` is the defect formation energy divided by the number of defects [equation 2 from the paper](https://www.nature.com/articles/s41524-023-01062-z#Sec5)
- `band_gap` is the HOMO-LUMO gap for the structures computed without spin
- `band_gap_{minority,majority}` are the HOMO-LUMO gaps for minority and majority spin channels for the structures computed with spin

**Comment by hongshuh** [comment]
Thanks!

**Comment by kazeevn** [comment]
@hongshuh hi! Hope you didn't encounter any further problems) I'm curious what you do with our data. Would you be up to have a chat and see whether there are ares in which we can collaborate?

**Comment by hongshuh** [comment]
@kazeevn I am doing a language model for materials property prediction, I was thinking whether there is a way to applied on the defect. It would be great to have a chat with you, we can connect via my email: hongshuh@andrew.cmu.edu

**Comment by kazeevn** [comment]
Our colleagues have found a mistake in data preprocessing, affecting formation energy for hBN and BP.  It's been fixed - I've updated both this repository and the [Constructor page](https://research.constructor.tech/open/2d-materials-point-defects).

There is also a slight data format change. To [avoid](https://github.com/materialsproject/pymatgen/issues/455) [confusion](https://github.com/HSE-LAMBDA/ai4material_design/blob/main/notebooks/band_gap_methods_comparison_WSe2.ipynb), we switched the column name from `band_gap` to `homo_lumo_gap`
